name: Daily AI Model Mailer

on:
  schedule:
    - cron: "0 2 * * *" # 7:30 AM IST
  workflow_dispatch:

jobs:
  send-image:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

- name: Install dependencies
  run: |
    pip install --upgrade pip
    pip install --upgrade --force-reinstall --no-cache-dir -r requirements.txt


      - name: Run the main script
        run: python main.py
