name: Daily AI Image Mailer

on:
  schedule:
    - cron: '0 4 * * *'  # Every day at 9:30 AM IST (4 AM UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python main.py
